/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlurCard: typeof import('./src/components/ui/BlurCard.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    Button: typeof import('primevue/button')['default']
    CandidateCard: typeof import('./src/components/ui/CandidateCard.vue')['default']
    DocumentViewer: typeof import('./src/components/ui/DocumentViewer.vue')['default']
    FilterButton: typeof import('./src/components/ui/FilterButton.vue')['default']
    GeometricBackground: typeof import('./src/components/GeometricBackground.vue')['default']
    JobCard: typeof import('./src/components/ui/JobCard.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    PageTitle: typeof import('./src/components/ui/PageTitle.vue')['default']
    PrimaryButton: typeof import('./src/components/ui/PrimaryButton.vue')['default']
    ProcessingScreen: typeof import('./src/components/ProcessingScreen.vue')['default']
    QRCodeCard: typeof import('./src/components/ui/QRCodeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenLayout: typeof import('./src/components/layout/ScreenLayout.vue')['default']
    ScrollArea: typeof import('./src/components/ui/ScrollArea.vue')['default']
    SettingCard: typeof import('./src/components/ui/SettingCard.vue')['default']
  }
}
